drop_train_features:
  - sunshine
  - solar_radiation
drop_features:
  - solar_power_capacity
  - ess_capacity
  - pcs_capacity
  - num_date_time
  - date_time
categorical_features:
  - building_type
  - heat_index
  - cluster
  - holiday
numerical_features:
  - temperature
  - rainfall
  - windspeed
  - humidity
  - total_area
  - cooling_area
lag_window: 3
