name: experiment
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - pip
  - python=3.10.11
  - pip:
    - black
    - flake8
    - isort
    - catboost==1.2
    - category-encoders==2.2.2
    - hydra-core==1.1.0
    - lightgbm==3.3.5
    - lightning-flash==0.7.5
    - lightning-utilities==0.8.0
    - matplotlib==3.7.1
    - numpy==1.23.5
    - optuna==2.10.1
    - pandas==1.1.5
    - plotly==5.15.0
    - prettytable==3.8.0
    - pytorch-tabnet==3.0.0
    - scikit-learn==0.24.2
    - scipy==1.10.1
    - torch==2.0.0
    - tqdm==4.65.0
    - wandb==0.15.4
    - xgboost==1.7.6
