params:
  max_iter: 10000
  l2_regularization: 0.01
  min_samples_leaf: 28
  learning_rate: 0.01
  early_stopping: auto
  
path: res/models/
name: histgbm
results: stratified-group-cross-validation-median-histgbm
early_stopping_rounds: 100
seed: 42
verbose_eval: 500
