params:
  objective: tweedie
  learning_rate: 0.05
  num_leaves: 100
  max_depth: 10
  min_data_in_leaf: 100
  bagging_fraction: 0.8
  feature_fraction: 0.8
  lambda_l1: 0.1
  lambda_l2: 0.1
  seed: 42
  verbose: -1
path: res/models/
name: lightgbm
results: 5fold-lightgbm-results.pkl
early_stopping_rounds: 100
num_boost_round: 10000
verbose_eval: 500