task_type: binary
n_splits: 10
params:
  objective: regression
  learning_rate: 0.05
  num_leaves: 16
  max_depth: -1
  seed: 42
  verbose: -1
multi_task: True
path: res/models/
name: lightgbm
results: lightgbm_results.txt
early_stopping_rounds: 100
num_boost_round: 10000
verbose_eval: 100