n_estimators: 100
seed: 42
path: res/models/
name: linearboosting
results: 2day-cross-validation-linearboosting.pkl
early_stopping_rounds: 100
num_boost_round: 10000
verbose_eval: 100
alpha: 1
is_custom_loss: False