n_splits: 10
path: res/models/
name: n_beats
results: n_beats-results
params:
  backbone: n_beats
  lr: 0.02
  optimizer: adamax
max_epochs: 5
batch_size: 64
max_encoder_length: 86
max_prediction_length: 1
gradient_clip_val: 0.01