params:
  lr: 0.1
  step_size: 50
  gamma: 1.5
  n_d: 16
  n_steps: 5
  n_a: 16
  lambda_sparse: 0.0001
  max_epochs: 1000
  patience: 100
  batch_size: 1024
  virtual_batch_size: 64
  num_workers: 1
  mask_type: entmax
  verbose: 10
  seed: 0
eval_name:
  - train
  - valid
eval_metric:
  - rmse
path: res/models/
name: tabnet
results: 2day-cross-validation-tabnet
teacher: 2day-cross-validation-xgboost
