params:
  eta: 0.02
  subsample: 0.8
  colsample_bytree: 0.8
  alpha: 0.1
  lambda: 0.1
  seed: 42
  tree_method: gpu_hist
  objective: reg:squarederror
multi_task: False
path: res/models/
name: xgboost
results: 3day-cross-validation-xgboost.pkl
early_stopping_rounds: 100
num_boost_round: 10000
verbose_eval: 100
alpha: 1
is_custom_loss: True