defaults:
  - _self_
  - data: dataset
  - features: features
  - models: lightgbm
  - hydra: default
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

output:
  path: output
  name: lightgbm-5tscv-solar-ensemble.csv
  submit: sample_submission.csv

ensemble:
  - lightgbm-2022-08-01-solar.csv
  - lightgbm-2022-08-05-solar.csv
  - lightgbm-2022-08-10-solar.csv
  - lightgbm-2022-08-15-solar.csv
  - lightgbm-2022-08-20-solar.csv
