defaults:
  - _self_
  - data: dataset
  - features: features
  - models: lightgbm
  - hydra: default
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

output:
  path: output
  name: stratified-group-cross-validation-median-final-ensemble.csv
  submit: sample_submission.csv
  tabnet: cross-validation-median-tabnet-student.csv

oofs:
  - stratified-group-cross-validation-median-xgboost.pkl
  - stratified-group-cross-validation-median-lightgbm.pkl
  - stratified-group-cross-validation-median-catboost.pkl
  - stratified-group-cross-validation-fe-catboost.pkl
preds:
  - stratified-group-cross-validation-median-xgboost.csv
  - stratified-group-cross-validation-median-lightgbm.csv
  - stratified-group-cross-validation-median-catboost.csv
  - stratified-group-cross-validation-fe-catboost.csv
median_preds:
  - stratified-group-cross-validation-fe-xgboost.csv
  - stratified-group-cross-validation-fe-lightgbm.csv
  - stratified-group-cross-validation-fe-catboost.csv