defaults:
  - _self_
  - data: dataset
  - features: features
  - models: lightgbm
  - hydra: default
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

output:
  path: output
  name: 2day-cross-validation-tree-cluster-ensemble.csv
  submit: sample_submission.csv

oofs:
  - 2day-cross-validation-cluster-xgboost.pkl
  - 2day-cross-validation-cluster-lightgbm.pkl
  - 2day-cross-validation-cluster-catboost.pkl
preds:
  - 2day-cross-validation-cluster-xgboost.csv
  - 2day-cross-validation-cluster-lightgbm.csv
  - 2day-cross-validation-cluster-catboost.csv
