defaults:
  - _self_
  - data: dataset
  - features: features
  - models: lightgbm
  - hydra: default
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

output:
  path: output
  name: 1day-cross-validation-tree-ensemble.csv
  submit: sample_submission.csv

oofs:
  - 1day-cross-validation-xgboost.pkl
  - 1day-cross-validation-catboost.pkl
  - 1day-cross-validation-lightgbm.pkl
preds:
  - 1day-cross-validation-xgboost.csv
  - 1day-cross-validation-catboost.csv
  - 1day-cross-validation-lightgbm.csv
