defaults:
  - _self_
  - data: dataset
  - features: features
  - models: lightgbm
  - hydra: default
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

output:
  path: output
  name: lightgbm-5tscv-ensemble.csv
  submit: sample_submission.csv

ensemble:
  preds1: lightgbm-2022-08-01.csv
  preds2: lightgbm-2022-08-05.csv
  preds3: lightgbm-2022-08-10.csv
  preds4: lightgbm-2022-08-15.csv
  preds5: lightgbm-2022-08-20.csv
