defaults:
  - _self_
  - data: dataset
  - features: features
  - models: lightgbm
  - hydra: default
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

output:
  path: output
  name: building-cross-validation-lightgbm-ensemble.csv
  submit: sample_submission.csv

oofs:
  - building-cross-validation-lightgbm-loss.pkl
  - building-cross-validation-lightgbm.pkl
preds:
  - building-cross-validation-lightgbm-loss.csv
  - building-cross-validation-lightgbm.csv

