defaults:
  - _self_
  - data: dataset
  - features: features
  - models: lightgbm
  - hydra: default
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

output:
  path: output
  name: 2day-cross-validation-tree-tabnet-ensemble.csv
  submit: sample_submission.csv
  tabnet: 5fold-tabnet-student-ensemble.csv

oofs:
  - 2day-cross-validation-xgboost.pkl
  - 2day-cross-validation-lightgbm.pkl
  - 2day-cross-validation-catboost.pkl
preds:
  - 2day-cross-validation-xgboost.csv
  - 2day-cross-validation-lightgbm.csv
  - 2day-cross-validation-catboost.csv

