defaults:
  - _self_
  - data: dataset
  - features: features
  - models: n_beats
  - hydra: custom
  - log: wandb
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

output:
  path: output
  submission: sample_submission.csv
  name: n_beats-forcasting.csv