defaults:
  - _self_
  - data: dataset
  - features: features
  - models: tabnet
  - hydra: default
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

output:
  path: output
  name: 5fold-tabnet-student-ensemble.csv
  submit: sample_submission.csv

oofs:
  - 2day-cross-validation-xgboost.pkl
  - 2day-cross-validation-lightgbm.pkl
  - 2day-cross-validation-catboost.pkl
  - 2day-cross-validation-cluster-xgboost.pkl
  - 2day-cross-validation-cluster-lightgbm.pkl
  - 2day-cross-validation-cluster-catboost.pkl
preds:
  - 2day-cross-validation-xgboost.csv
  - 2day-cross-validation-lightgbm.csv
  - 2day-cross-validation-catboost.csv
  - 2day-cross-validation-cluster-xgboost.csv
  - 2day-cross-validation-cluster-lightgbm.csv
  - 2day-cross-validation-cluster-catboost.csv