defaults:
  - _self_
  - data: dataset
  - features: features
  - models: tabnet
  - hydra: default
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

output:
  path: output
  name: cross-validation-median-tabnet-student.csv
  submit: sample_submission.csv

oofs:
  - stratified-group-cross-validation-median-xgboost.pkl
  - stratified-group-cross-validation-median-lightgbm.pkl
  - stratified-group-cross-validation-median-catboost.pkl
preds:
  - stratified-group-cross-validation-median-xgboost.csv
  - stratified-group-cross-validation-median-lightgbm.csv
  - stratified-group-cross-validation-median-catboost.csv